
package com.cucharitas.versioning.poc.v1.addressbook;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getAddress", targetNamespace = "http://www.cipal.be/poc/v1/addressbook", wsdlLocation = "http://localhost:8080/addressbook/getAddress.wsdl")
public class GetAddress
    extends Service
{

    private final static URL GETADDRESS_WSDL_LOCATION;
    private final static WebServiceException GETADDRESS_EXCEPTION;
    private final static QName GETADDRESS_QNAME = new QName("http://www.cipal.be/poc/v1/addressbook", "getAddress");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/addressbook/getAddress.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETADDRESS_WSDL_LOCATION = url;
        GETADDRESS_EXCEPTION = e;
    }

    public GetAddress() {
        super(__getWsdlLocation(), GETADDRESS_QNAME);
    }

    public GetAddress(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETADDRESS_QNAME, features);
    }

    public GetAddress(URL wsdlLocation) {
        super(wsdlLocation, GETADDRESS_QNAME);
    }

    public GetAddress(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETADDRESS_QNAME, features);
    }

    public GetAddress(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAddress(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressbookProvider
     */
    @WebEndpoint(name = "getAddressPort")
    public AddressbookProvider getGetAddressPort() {
        return super.getPort(new QName("http://www.cipal.be/poc/v1/addressbook", "getAddressPort"), AddressbookProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressbookProvider
     */
    @WebEndpoint(name = "getAddressPort")
    public AddressbookProvider getGetAddressPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cipal.be/poc/v1/addressbook", "getAddressPort"), AddressbookProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETADDRESS_EXCEPTION!= null) {
            throw GETADDRESS_EXCEPTION;
        }
        return GETADDRESS_WSDL_LOCATION;
    }

}
